# Generated by Django 5.2.3 on 2025-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('local_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('types', models.CharField(max_length=100)),
            ],
        ),
    ]
